<?php

declare(strict_types=1);

// Shared bootstrap for web requests, CLI commands, and tests.
require_once __DIR__ . '/PortalI18nCatalog.php';
require_once __DIR__ . '/VideoWalls.php';
require_once __DIR__ . '/VideoWallPages.php';
require_once __DIR__ . '/VideoWallTranslations.php';
require_once __DIR__ . '/Config.php';
require_once __DIR__ . '/DB.php';
require_once __DIR__ . '/PortalSettings.php';
require_once __DIR__ . '/MapTilesService.php';
require_once __DIR__ . '/Util.php';
require_once __DIR__ . '/I18n.php';
require_once __DIR__ . '/Crypto.php';
require_once __DIR__ . '/Audit.php';
require_once __DIR__ . '/TokenService.php';
require_once __DIR__ . '/Auth.php';
require_once __DIR__ . '/Csrf.php';
require_once __DIR__ . '/DvrClient.php';
require_once __DIR__ . '/PortalUpdateService.php';
require_once __DIR__ . '/Repo.php';
require_once __DIR__ . '/Api/PortalApi.php';
require_once __DIR__ . '/Pages/MapPages.php';
require_once __DIR__ . '/Api/DashboardApi.php';
require_once __DIR__ . '/Api/UsersApi.php';
require_once __DIR__ . '/Api/GroupsApi.php';
require_once __DIR__ . '/Api/ServersApi.php';
require_once __DIR__ . '/Api/CamerasApi.php';
require_once __DIR__ . '/Api/AgentsApi.php';
require_once __DIR__ . '/Api/AuditApi.php';
require_once __DIR__ . '/Pages/DashboardPages.php';
require_once __DIR__ . '/Pages/SettingsPages.php';
require_once __DIR__ . '/Pages/DvrPages.php';
require_once __DIR__ . '/Pages/LoginPages.php';
require_once __DIR__ . '/Pages/UsersPages.php';
require_once __DIR__ . '/Pages/GroupsPages.php';
require_once __DIR__ . '/Support/DataHelpers.php';
require_once __DIR__ . '/Pages/AgentsPages.php';
require_once __DIR__ . '/Ui/FormsUi.php';
require_once __DIR__ . '/Pages/CamerasPages.php';
require_once __DIR__ . '/Pages/CameraImportPages.php';
require_once __DIR__ . '/Support/CameraFields.php';
require_once __DIR__ . '/Pages/AuditPages.php';
require_once __DIR__ . '/Pages/ViewerPages.php';
require_once __DIR__ . '/AuthBackend.php';
require_once __DIR__ . '/Ui/LayoutUi.php';
require_once __DIR__ . '/Ui/GroupTreeUi.php';
require_once __DIR__ . '/Support/ListQueries.php';
require_once __DIR__ . '/Ui/TablesUi.php';
require_once __DIR__ . '/Support/PlaybackUrls.php';
require_once __DIR__ . '/Support/CameraStatus.php';
require_once __DIR__ . '/App.php';
require_once __DIR__ . '/Cli.php';
