<?php

declare(strict_types=1);

namespace SesamePortal;

use InvalidArgumentException;
use PDO;

final class VideoWalls
{
    public const MAX_DIMENSION = 6;

    public static function migrate(): void
    {
        $id = match (DB::driver()) {
            'pgsql' => 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
            'mysql' => 'BIGINT AUTO_INCREMENT PRIMARY KEY',
            default => 'INTEGER PRIMARY KEY AUTOINCREMENT',
        };
        $userId = DB::driver() === 'sqlite' ? 'INTEGER' : 'BIGINT';
        $suffix = DB::driver() === 'mysql' ? ' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4' : '';
        DB::pdo()->exec("CREATE TABLE IF NOT EXISTS video_walls (
            id {$id},
            user_id {$userId} NOT NULL,
            name VARCHAR(255) NOT NULL,
            grid_rows INTEGER NOT NULL DEFAULT 3,
            grid_cols INTEGER NOT NULL DEFAULT 3,
            camera_ids TEXT NOT NULL,
            created_at VARCHAR(64) NOT NULL,
            updated_at VARCHAR(64) NOT NULL,
            CONSTRAINT fk_video_walls_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        ){$suffix}");
    }

    public static function find(array $user, int $id): ?array
    {
        $stmt = DB::pdo()->prepare('SELECT w.*, u.login AS owner_login FROM video_walls w JOIN users u ON u.id = w.user_id WHERE w.id = ?');
        $stmt->execute([$id]);
        $wall = $stmt->fetch();
        return $wall && ($user['role'] === 'admin' || (int)$wall['user_id'] === (int)$user['id']) ? $wall : null;
    }

    public static function page(array $user, int $page = 1, int $pageSize = 25): array
    {
        $where = $user['role'] === 'admin' ? '' : ' WHERE w.user_id = ?';
        $params = $user['role'] === 'admin' ? [] : [(int)$user['id']];
        $count = DB::pdo()->prepare('SELECT COUNT(*) FROM video_walls w' . $where);
        $count->execute($params);
        $total = (int)$count->fetchColumn();
        $pageSize = max(1, min(100, $pageSize));
        $page = max(1, min($page, max(1, (int)ceil($total / $pageSize))));
        $stmt = DB::pdo()->prepare('SELECT w.*, u.login AS owner_login FROM video_walls w JOIN users u ON u.id = w.user_id' . $where . ' ORDER BY w.updated_at DESC, w.id DESC LIMIT ? OFFSET ?');
        foreach ([...$params, $pageSize, ($page - 1) * $pageSize] as $i => $value) {
            $stmt->bindValue($i + 1, $value, PDO::PARAM_INT);
        }
        $stmt->execute();
        return ['rows' => $stmt->fetchAll(), 'total' => $total, 'page' => $page, 'pageSize' => $pageSize];
    }

    public static function ids(array $wall): array
    {
        $ids = json_decode((string)($wall['camera_ids'] ?? '[]'), true);
        return is_array($ids) ? array_values(array_unique(array_map('intval', $ids))) : [];
    }

    public static function owner(array $wall): array
    {
        $stmt = DB::pdo()->prepare('SELECT id, role, blocked FROM users WHERE id = ?');
        $stmt->execute([(int)$wall['user_id']]);
        return $stmt->fetch() ?: ['id' => 0, 'role' => 'user', 'blocked' => 1];
    }

    public static function cameras(array $user, array $ids): array
    {
        if (!empty($user['blocked'])) {
            return [];
        }
        $result = [];
        foreach (Repo::accessibleCamerasByIds($user, $ids) as $camera) {
            $result[(int)$camera['id']] = $camera;
        }
        return $result;
    }

    public static function save(array $user, ?array $current, array $input): array
    {
        $name = array_key_exists('name', $input) ? $input['name'] : ($current['name'] ?? '');
        if (!is_string($name) || trim($name) === '' || (function_exists('mb_strlen') ? mb_strlen(trim($name)) : strlen(trim($name))) > 255) {
            throw new InvalidArgumentException('wall.invalidName');
        }
        $rawRows = array_key_exists('rows', $input) ? $input['rows'] : ($current['grid_rows'] ?? 3);
        $rawCols = array_key_exists('columns', $input) ? $input['columns'] : ($current['grid_cols'] ?? 3);
        $rows = is_int($rawRows) || is_string($rawRows) ? filter_var($rawRows, FILTER_VALIDATE_INT) : false;
        $cols = is_int($rawCols) || is_string($rawCols) ? filter_var($rawCols, FILTER_VALIDATE_INT) : false;
        if ($rows === false || $cols === false || $rows < 1 || $rows > self::MAX_DIMENSION || $cols < 1 || $cols > self::MAX_DIMENSION) {
            throw new InvalidArgumentException('wall.invalidGrid');
        }
        $ids = array_key_exists('cameraIds', $input) ? $input['cameraIds'] : ($current ? self::ids($current) : []);
        if (!is_array($ids) || !array_is_list($ids) || !$ids || count($ids) > $rows * $cols) {
            throw new InvalidArgumentException('wall.invalidSelection');
        }
        foreach ($ids as &$id) {
            if ((!is_int($id) && !is_string($id)) || filter_var($id, FILTER_VALIDATE_INT) === false || (int)$id <= 0) {
                throw new InvalidArgumentException('wall.invalidSelection');
            }
            $id = (int)$id;
        }
        unset($id);
        if (count(array_unique($ids)) !== count($ids)) {
            throw new InvalidArgumentException('wall.invalidSelection');
        }
        $owner = $current ? self::owner($current) : $user;
        if (count(self::cameras($owner, $ids)) !== count($ids) || count(self::cameras($user, $ids)) !== count($ids)) {
            throw new InvalidArgumentException('wall.cameraUnavailable');
        }
        $now = Util::now();
        $values = [trim($name), $rows, $cols, json_encode($ids), $now];
        if ($current) {
            $id = (int)$current['id'];
            DB::pdo()->prepare('UPDATE video_walls SET name = ?, grid_rows = ?, grid_cols = ?, camera_ids = ?, updated_at = ? WHERE id = ? AND user_id = ?')
                ->execute([...$values, $id, (int)$owner['id']]);
        } else {
            DB::pdo()->prepare('INSERT INTO video_walls(name, grid_rows, grid_cols, camera_ids, updated_at, user_id, created_at) VALUES(?, ?, ?, ?, ?, ?, ?)')
                ->execute([...$values, (int)$user['id'], $now]);
            $id = DB::lastInsertId('video_walls');
        }
        Audit::logForUser((int)$user['id'], $current ? 'video_wall.update' : 'video_wall.create', 'id=' . $id . ' owner_id=' . (int)$owner['id'] . ' cameras=' . count($ids) . ' ip=' . Audit::clientIp());
        return self::find($user, $id);
    }

    public static function delete(array $user, array $wall): void
    {
        DB::pdo()->prepare('DELETE FROM video_walls WHERE id = ? AND user_id = ?')->execute([(int)$wall['id'], (int)$wall['user_id']]);
        Audit::logForUser((int)$user['id'], 'video_wall.delete', 'id=' . (int)$wall['id'] . ' ip=' . Audit::clientIp());
    }

    public static function payload(array $wall): array
    {
        return [
            'id' => (int)$wall['id'], 'userId' => (int)$wall['user_id'], 'ownerLogin' => $wall['owner_login'],
            'name' => $wall['name'], 'rows' => (int)$wall['grid_rows'], 'columns' => (int)$wall['grid_cols'],
            'cameraIds' => self::ids($wall), 'createdAt' => $wall['created_at'], 'updatedAt' => $wall['updated_at'],
        ];
    }
}
